#!/bin/bash

##python -W ignore transfer_attack.py --model deeplabv3_resnet50 --enable_vis --vis_port 28337 --gpu_id 0 --year 2012_aug --crop_val --lr 0.01 --crop_size 473 --batch_size 16 --output_stride 16 --test_only --save_val_results --attack cospgd --iterations 10 --attacked_model deeplabv3_resnet50 --attacking_model pspnet_resnet50
##python -W ignore transfer_attack.py --model deeplabv3_resnet50 --enable_vis --vis_port 28337 --gpu_id 0 --year 2012_aug --crop_val --lr 0.01 --crop_size 473 --batch_size 16 --output_stride 16 --test_only --save_val_results --attack cospgd --iterations 20 --attacked_model deeplabv3_resnet50 --attacking_model pspnet_resnet50
##python -W ignore transfer_attack.py --model deeplabv3_resnet50 --enable_vis --vis_port 28337 --gpu_id 0 --year 2012_aug --crop_val --lr 0.01 --crop_size 473 --batch_size 16 --output_stride 16 --test_only --save_val_results --attack cospgd --iterations 40 --attacked_model deeplabv3_resnet50 --attacking_model pspnet_resnet50
##python -W ignore transfer_attack.py --model deeplabv3_resnet50 --enable_vis --vis_port 28337 --gpu_id 0 --year 2012_aug --crop_val --lr 0.01 --crop_size 473 --batch_size 16 --output_stride 16 --test_only --save_val_results --attack segpgd --iterations 10 --attacked_model deeplabv3_resnet50 --attacking_model pspnet_resnet50
##python -W ignore transfer_attack.py --model deeplabv3_resnet50 --enable_vis --vis_port 28337 --gpu_id 0 --year 2012_aug --crop_val --lr 0.01 --crop_size 473 --batch_size 16 --output_stride 16 --test_only --save_val_results --attack segpgd --iterations 20 --attacked_model deeplabv3_resnet50 --attacking_model pspnet_resnet50
##python -W ignore transfer_attack.py --model deeplabv3_resnet50 --enable_vis --vis_port 28337 --gpu_id 0 --year 2012_aug --crop_val --lr 0.01 --crop_size 473 --batch_size 16 --output_stride 16 --test_only --save_val_results --attack segpgd --iterations 40 --attacked_model deeplabv3_resnet50 --attacking_model pspnet_resnet50

python -W ignore transfer_attack.py --model deeplabv3_resnet50 --enable_vis --vis_port 28337 --gpu_id 0 --year 2012_aug --crop_val --lr 0.01 --crop_size 473 --batch_size 16 --output_stride 16 --test_only --save_val_results --attack cospgd --iterations 10 --attacking_model deeplabv3_resnet50 --attacked_model pspnet_resnet50
python -W ignore transfer_attack.py --model deeplabv3_resnet50 --enable_vis --vis_port 28337 --gpu_id 0 --year 2012_aug --crop_val --lr 0.01 --crop_size 473 --batch_size 16 --output_stride 16 --test_only --save_val_results --attack cospgd --iterations 20 --attacking_model deeplabv3_resnet50 --attacked_model pspnet_resnet50
python -W ignore transfer_attack.py --model deeplabv3_resnet50 --enable_vis --vis_port 28337 --gpu_id 0 --year 2012_aug --crop_val --lr 0.01 --crop_size 473 --batch_size 16 --output_stride 16 --test_only --save_val_results --attack cospgd --iterations 40 --attacking_model deeplabv3_resnet50 --attacked_model pspnet_resnet50
python -W ignore transfer_attack.py --model deeplabv3_resnet50 --enable_vis --vis_port 28337 --gpu_id 0 --year 2012_aug --crop_val --lr 0.01 --crop_size 473 --batch_size 16 --output_stride 16 --test_only --save_val_results --attack segpgd --iterations 10 --attacking_model deeplabv3_resnet50 --attacked_model pspnet_resnet50
python -W ignore transfer_attack.py --model deeplabv3_resnet50 --enable_vis --vis_port 28337 --gpu_id 0 --year 2012_aug --crop_val --lr 0.01 --crop_size 473 --batch_size 16 --output_stride 16 --test_only --save_val_results --attack segpgd --iterations 20 --attacking_model deeplabv3_resnet50 --attacked_model pspnet_resnet50
python -W ignore transfer_attack.py --model deeplabv3_resnet50 --enable_vis --vis_port 28337 --gpu_id 0 --year 2012_aug --crop_val --lr 0.01 --crop_size 473 --batch_size 16 --output_stride 16 --test_only --save_val_results --attack segpgd --iterations 40 --attacking_model deeplabv3_resnet50 --attacked_model pspnet_resnet50